on: push
jobs:
  first-job:
    strategy:
      matrix:
        version: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: node --version
      - run: npm --version
